WIDTH = 600
HEIGHT = 400
FPS = 60
HEART_SPEED = 5
MARGIN = 5
MAX_HP = 92
INVINCIBILITY_DURATION = 0
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

# Define game state constants
STATE_MENU = "MENU"
STATE_ATTACK = "ATTACK"
STATE_DIALOG = "DIALOG"
STATE_GAME_OVER = "GAME_OVER"
STATE_VICTORY = "VICTORY"
STATE_ACT = "ACT"
STATE_ACT_SANS = "ACT_SANS"
STATE_ACT_RESPONSE = "ACT_RESPONSE"
STATE_ITEM = "ITEM"
STATE_SPARE = "SPARE"